export const GET_PROJECTS = 'GET_PROJECTS';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';